/// <reference lib="webworker" />
import { clientsClaim } from 'workbox-core';
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';

declare let self: ServiceWorkerGlobalScope;

// Take over immediately
self.skipWaiting();
clientsClaim();

// Precache static assets generated by Vite
cleanupOutdatedCaches();
precacheAndRoute(self.__WB_MANIFEST);

// Supabase API Cache (Network First)
registerRoute(
  /^https:\/\/ajqzyygzgjrydxilzzto\.supabase\.co\/rest\/v1\/.*/i,
  new NetworkFirst({
    cacheName: 'supabase-api-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24 // 1 day
      })
    ]
  })
);

// Image Cache (Cache First)
registerRoute(
  /\.(?:png|jpg|jpeg|svg|gif|webp)$/,
  new CacheFirst({
    cacheName: 'image-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 24 * 30 // 30 days
      })
    ]
  })
);

// --------------------------------------------------------
// BACKGROUND PUSH NOTIFICATION LOGIC
// --------------------------------------------------------

self.addEventListener('push', (event) => {
  console.log('[Service Worker] Push Received (Background/Foreground).');

  let data: any = {};
  if (event.data) {
    try {
      data = event.data.json();
    } catch (e) {
      data = { body: event.data.text() };
    }
  }

  const baseUrl = self.location.origin;
  const title = data.title || 'KPH News';
  
  const options: NotificationOptions = {
    body: data.body || 'You have a new notification.',
    icon: data.icon || (baseUrl + '/logo192.png'),
    badge: baseUrl + '/logo192.png',
    data: data.url || '/', // URL to open on click
    vibrate: [200, 100, 200],
    requireInteraction: true // Keep notification on screen until user interacts
  };

  if (data.image && typeof data.image === 'string' && data.image.startsWith('http')) {
    options.image = data.image;
  }

  // Wrap in a try-catch inside waitUntil to guarantee a fallback notification
  event.waitUntil(
    self.registration.showNotification(title, options).catch((err) => {
      console.error('[Service Worker] Failed to show primary notification', err);
      // Fallback guarantees we don't violate iOS/Android requirements of showing a notification on push
      return self.registration.showNotification('KPH News', {
        body: 'A new article has been published.',
        icon: baseUrl + '/logo192.png',
        data: '/',
      });
    })
  );
});

self.addEventListener('notificationclick', (event) => {
  console.log('[Service Worker] Notification click Received.');
  event.notification.close();
  const urlToOpen = event.notification.data || '/';
  
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      // If a window tab matching the targeted URL already exists, focus that
      for (let i = 0; i < clientList.length; i++) {
        const client = clientList[i];
        if (client.url === urlToOpen && 'focus' in client) {
          return client.focus();
        }
      }
      // If no window tab is open, open a new tab/window
      if (self.clients.openWindow) {
        return self.clients.openWindow(urlToOpen);
      }
    })
  );
});
